package dev.razorni.hcfactions.extras.framework;

import dev.razorni.hcfactions.extras.framework.extra.Configs;

public class Config {
    public static String DEATH_VOID;
    public static double ARCHER_TAG_DAMAGE;
    public static String RELATION_ALLIED;
    public static String DEATH_VOID_KILLER;
    public static String DEATH_EXPLOSION;
    public static double ARCHER_TAGGED_DAMAGE;
    public static String NOT_IN_TEAM;
    public static String SYSTEAM_COLOR_GLOWSTONE;
    public static String RELATION_INVINCIBLES;
    public static String RELATION_STAFF;
    public static String DEATH_FALL_KILLER;
    public static double ARCHER_HALF_FORCE_DAMAGE;
    public static String INSUFFICIENT_ROLE;
    public static String DEATH_ENTITY;
    public static String DEATH_LOGGER;
    public static String DEATH_PROJECTILE_KILLER;
    public static String RELATION_TEAMMATE;
    public static double ARCHER_TAGGED_MULTIPLIER;
    public static String DEATH_FIRE;
    public static String RELATION_KING;
    public static int NETHER_MULTIPLIER;
    public static String RELATION_PVPTIMER;
    public static String TEAM_ALREADY_EXISTS;
    public static String DEATH_LOGGER_KILLER;
    public static String PREFIX_STAFF;
    public static String DEATH_KILLER;
    public static String PLAYER_ONLY;
    public static String NOT_VALID_NUMBER;
    public static String RELATION_ENEMY;
    public static String DEATH_LIGHTNING;
    public static String RELATION_ARCHERTAG;
    public static String DEATH_PROJECTILE;
    public static int TEAM_NAME_MIN_LENGTH;
    public static String DEATH_DEFAULT;
    public static String DEATH_LAVA;
    public static String RELATION_SOTW;
    public static String TEAM_NOT_FOUND;
    public static double DTR_REGEN_PER_MIN;
    public static String DEATH_SUFFOCATION;
    public static int SMELT_MULTIPLIER;
    public static String PLAYER_NOT_FOUND;
    public static String DEATH_DROWN;
    public static String DEATH_WITHER;
    public static String PREFIX_KING;
    public static String DEATH_MAGIC;
    public static String DEATH_FORMAT;
    public static String ALREADY_IN_TEAM;
    public static double DTR_TAKE_DEATH;
    public static String DEATH_BACKSTABBED;
    public static String DEATH_POISON;
    public static String DEATH_STARVATION;
    public static String RELATION_FOCUSED;
    public static String DEATH_FALL;
    public static int TEAM_NAME_MAX_LENGTH;
    public static String INSUFFICIENT_PERM;
    public static String DEATH_CONTACT;
    public static String SYSTEAM_COLOR_ORE_MOUNTAIN;

    public Config(Configs configs) {
        Config.PLAYER_NOT_FOUND = configs.getLanguageConfig().getString("GLOBAL_COMMANDS.PLAYER_NOT_FOUND");
        Config.PLAYER_ONLY = configs.getLanguageConfig().getString("GLOBAL_COMMANDS.PLAYER_ONLY");
        Config.INSUFFICIENT_PERM = configs.getLanguageConfig().getString("GLOBAL_COMMANDS.INSUFFICIENT_PERMISSION");
        Config.NOT_VALID_NUMBER = configs.getLanguageConfig().getString("GLOBAL_COMMANDS.NOT_VALID_NUMBER");
        Config.NOT_IN_TEAM = configs.getLanguageConfig().getString("TEAM_COMMAND.NOT_IN_TEAM");
        Config.ALREADY_IN_TEAM = configs.getLanguageConfig().getString("TEAM_COMMAND.ALREADY_IN_TEAM");
        Config.TEAM_ALREADY_EXISTS = configs.getLanguageConfig().getString("TEAM_COMMAND.TEAM_ALREADY_EXISTS");
        Config.TEAM_NOT_FOUND = configs.getLanguageConfig().getString("TEAM_COMMAND.TEAM_NOT_FOUND");
        Config.INSUFFICIENT_ROLE = configs.getLanguageConfig().getString("TEAM_COMMAND.INSUFFICIENT_ROLE");
        Config.RELATION_TEAMMATE = configs.getTeamConfig().getString("RELATION_COLOR.TEAMMATE");
        Config.RELATION_ALLIED = configs.getTeamConfig().getString("RELATION_COLOR.ALLIED");
        Config.RELATION_ENEMY = configs.getTeamConfig().getString("RELATION_COLOR.ENEMY");
        Config.RELATION_FOCUSED = configs.getTeamConfig().getString("RELATION_COLOR.FOCUSED");
        Config.RELATION_ARCHERTAG = configs.getTeamConfig().getString("RELATION_COLOR.ARCHER_TAG");
        Config.RELATION_PVPTIMER = configs.getTeamConfig().getString("RELATION_COLOR.PVP_TIMER");
        Config.RELATION_INVINCIBLES = configs.getTeamConfig().getString("RELATION_COLOR.INVINCIBILITY");
        Config.RELATION_KING = configs.getTeamConfig().getString("RELATION_COLOR.KING");
        Config.RELATION_SOTW = configs.getTeamConfig().getString("RELATION_COLOR.SOTW");
        Config.RELATION_STAFF = configs.getTeamConfig().getString("RELATION_COLOR.STAFF");
        Config.PREFIX_STAFF = configs.getTeamConfig().getString("RELATION_COLOR.STAFF_PREFIX");
        Config.PREFIX_KING = configs.getTeamConfig().getString("RELATION_COLOR.KING_PREFIX");
        Config.SYSTEAM_COLOR_ORE_MOUNTAIN = configs.getTeamConfig().getString("SYSTEM_TEAMS.ORE_MOUNTAIN");
        Config.SYSTEAM_COLOR_GLOWSTONE = configs.getTeamConfig().getString("SYSTEM_TEAMS.GLOWSTONE");
        Config.TEAM_NAME_MIN_LENGTH = configs.getTeamConfig().getInt("TEAM_NAME.MIN_LENGTH");
        Config.TEAM_NAME_MAX_LENGTH = configs.getTeamConfig().getInt("TEAM_NAME.MAX_LENGTH");
        Config.NETHER_MULTIPLIER = configs.getConfig().getInt("MULTIPLIERS.NETHER_MULTIPLIER");
        Config.SMELT_MULTIPLIER = configs.getConfig().getInt("MULTIPLIERS.SMELT_MULTIPLIER");
        Config.DTR_REGEN_PER_MIN = configs.getTeamConfig().getDouble("TEAM_DTR.REGEN_PER_MIN");
        Config.DTR_TAKE_DEATH = configs.getTeamConfig().getDouble("TEAM_DTR.DEATH_DTR");
        Config.ARCHER_TAG_DAMAGE = configs.getClassesConfig().getDouble("ARCHER_CLASS.ARCHER_TAG_DAMAGE") * 2.0;
        Config.ARCHER_HALF_FORCE_DAMAGE = configs.getClassesConfig().getDouble("ARCHER_CLASS.ARCHER_HALF_FORCE") * 2.0;
        Config.ARCHER_TAGGED_DAMAGE = configs.getClassesConfig().getDouble("ARCHER_CLASS.ALREADY_TAGGED_DAMAGE") * 2.0;
        Config.ARCHER_TAGGED_MULTIPLIER = configs.getClassesConfig().getDouble("ARCHER_CLASS.TAGGED_DAMAGE_MULTIPLIER");
        Config.DEATH_FORMAT = configs.getLanguageConfig().getString("DEATH_LISTENER.PLAYER_FORMAT");
        Config.DEATH_KILLER = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.KILLER");
        Config.DEATH_ENTITY = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.ENTITY");
        Config.DEATH_FALL = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.FALL");
        Config.DEATH_FALL_KILLER = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.FALL_KILLER");
        Config.DEATH_LIGHTNING = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.LIGHTNING");
        Config.DEATH_VOID = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.VOID");
        Config.DEATH_VOID_KILLER = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.VOID_KILLER");
        Config.DEATH_EXPLOSION = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.EXPLOSION");
        Config.DEATH_CONTACT = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.CONTACT");
        Config.DEATH_WITHER = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.WITHER");
        Config.DEATH_STARVATION = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.STARVATION");
        Config.DEATH_SUFFOCATION = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.SUFFOCATION");
        Config.DEATH_DROWN = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.DROWNED");
        Config.DEATH_POISON = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.POISON");
        Config.DEATH_FIRE = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.FIRE");
        Config.DEATH_LAVA = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.LAVA");
        Config.DEATH_LOGGER = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.LOGGER");
        Config.DEATH_LOGGER_KILLER = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.LOGGER_KILLER");
        Config.DEATH_BACKSTABBED = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.BACKSTABBED");
        Config.DEATH_PROJECTILE = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.PROJECTILE");
        Config.DEATH_PROJECTILE_KILLER = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.PROJECTILE_KILLER");
        Config.DEATH_MAGIC = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.MAGIC");
        Config.DEATH_DEFAULT = configs.getLanguageConfig().getString("DEATH_LISTENER.MESSAGES.DEFAULT");
    }

    public void get() {
    }
}